services:
  backend:
    image: aditya280102/python-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 13000:8000
    environment:
      GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: ${secrets.LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: ${secrets.LANGCHAIN_PROJECT}
      OPENAI_API_KEY: ${secrets.OPENAI_API_KEY}
      ALGORITHM: HS256
      JWT_SECRET_KEY: ${secrets.JWT_SECRET_KEY}
      DATABASE_URL: "postgresql://${secrets.DATABASE_USER}:${secrets.DATABASE_PASSWORD}@pg-hma-python-db/${secrets.DATABASE_NAME}"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      pg-hma-python-db: service_healthy
    networks:
      - hma-python-network
  
  pg-hma-python-db:
    image: postgres:alpine
    container_name: pg-hma-python-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - hma-python-network

networks:
  hma-python-network:
    driver: bridge